config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root 'splashs#index'
  resources :groups, only: [:index, :show, :new, :create] do
    resources :entities, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :groups
  validates :name, presence: true, uniqueness: true
  validates :amount,
            presence: true,
            format: {
              with: /\A\d+(\.\d{1,2})?\z/,
              message: 'must be a decimal value with up to 2 decimal places'
            },
            numericality: {
              greater_than_or_equal_to: 0
            }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :entitys
  # has_one_attached :icon
  validates :name, presence: true, uniqueness: { scope: :user_id, message: 'has already been taken for this user' }
  validates :icon, presence: true, format: { with: /.+\.png\z/, message: "must end with '.png'" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entitys, dependent: :destroy
  has_many :groups, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :password, :current_password)
    end
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_group

  def new
    @current_user = current_user
    @entity = Entity.new
    @groups = current_user.groups
  end

  def create
    @current_user = current_user
    @entity = Entity.new(name: params[:entity][:name], amount: params[:entity][:amount])
    @entity.user = @current_user
    @groups_id = params[:entity][:category_id]
    @groups_id.each do |category_id|
      group = Group.find(category_id)
      @entity.groups << group
    end
    if @entity.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  private

  def set_group
    @group = current_user.groups.find(params[:group_id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, category_id: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def new
    @current_user = current_user
    @group = Group.new
  end

  def create
    @current_user = current_user
    @group = Group.new(group_params)
    @group.user = @current_user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(request.params['id'])
    @current_user = current_user
    @entities = Entity.joins(:entities_groups).where(entities_groups: { group_id: @group.id },
                                                     user_id: @current_user.id).order(created_at: :desc)
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splashs_controller.rb
class SplashsController < ApplicationController
  def index
    # Empty action as the view is responsible for the  screen content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/new.html.erb
<%= form_with model: @entity, url: group_entities_path(@group), method: :post, local: true, html: { class: "new-entity-form" } do |f| %>
  <div class="new-entity-header">
    <div class ="back-arrow">
      <%= link_to group_path(@group) do %>
        <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "back-arrow-img" %>
      <% end %>
    </div>
    <h2>ADD EXPENSE</h2>
    <%= f.submit "ADD", class: "submit-new-entity" %>
  </div>
  <div class = "new-entity-body">
    <div class="field-name-new-entity">
      <%= f.text_field :name, autocomplete: "Entity name", placeholder: "Name", class: "login-field" %>
    </div>
    <div class="field-name-new-entity">
      <%= f.text_field :amount, autocomplete: "Amount", placeholder: "Amount", class: "login-field" %>
    </div>
    <div class="field-name-new-entity">
      <% @groups.each do |group| %>
        <p>
          <%= f.check_box :category_id, { multiple: true }, group.id, nil %>
          <%= group.name %>
        </p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/entitys/index.html.erb
<section class="categories-container">
  <div class="categories-header">
      <div class ="hamburger">
        <%= image_tag "hamburger.png", alt: "Hamburger Icon", class: "hamburger-img"%>
      </div>
      <h2>TRANSACTIONS</h2>
      <div class ="search">
        <%= image_tag "search.png", alt: "Search Icon", class: "search-img"%>
      </div>
  </div>
  <div class="categories-subheader">
      <div>
          <p class="left"> Most ancient</p>
      </div>
      <div>
      <p> Most recent</p>
      </div>
      <div class="dummy" >Not to show</div>
  </div>
  <ul class="entities">
     <% @entities.each do |entity| %>
        <li class="entity-container">
            <div class="entity-icon">
                <%= image_tag "piggy-bank.png", alt: "Entity Icon", class: "entity-img"%>
            </div>
            <div class="entity-name-container">
              <h3>
                <%= link_to entity.name, entity_path(entity), { class: "entity-name" } %>
              </h3>
              <p class="entity-updated">
                <%= entity.updated_at.strftime('%d %b %Y')%>
              </p>
            </div>
            <p class="entity-amount">$ <%= entity.amount%></p>
        </li>
    <% end %>
  </ul>
  <div class="new-category-container">
    <%= link_to "ADD CATEGORY", new_entity_path, class: "new-category" %>
  </div>
</section>

app/views/entitys/new.html.erb
<%= form_with model: @entity, url: entitys_path, method: :post, local: true, html: { class: "new-category-form" } do |f|%>
  <div class="new-category-header">
    <div class ="back-arrow">
      <%= link_to entitys_path do %>
      <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "back-arrow-img"%>
      <% end %>
    </div>
    <h2>ADD CATEGORY</h2>
    <%= f.submit "Create", class: "submit-new-category" %>
  </div>
   <div class="field-name-new-category">
    <%= f.text_field :name, autocomplete: "Entity name", placeholder: "Name", class: "login-field"%>
  </div>
<%end%>

app/views/groups/index.html.erb
<section class="categories-container">
  <div class="categories-header">
      <div class ="hamburger">
        <%= image_tag "hamburger.png", alt: "Hamburger Icon", class: "hamburger-img"%>
      </div>
      <h2>CATEGORIES</h2>
      <div class ="search">
        <%= image_tag "search.png", alt: "Search Icon", class: "search-img"%>
      </div>
  </div>
  <div class="categories-subheader">
      <div>
          <p class="left"> Most ancient</p>
      </div>
      <div>
      <p> Most recent</p>
      </div>
      <div class="dummy" >Not to show</div>
  </div>
  <ul class="groups">
     <% @groups.each do |group| %>
        <li class="group-container">
            <div class="group-icon">
                <%= image_tag group.icon, alt: "Group Icon", class: "group-img"%>
            </div>
            <div class="group-name-container">
              <h3>
                <%= link_to group.name, group_path(group), { class: "group-name" } %>
              </h3>
              <p class="group-updated">
                <%= group.updated_at.strftime('%d %b %Y')%>
              </p>
            </div>
            <p class="group-amount">$<%= group.entitys.sum(:amount) %></p>
        </li>
    <% end %>
  </ul>
  <div class="new-category-container">
    <%= link_to "ADD CATEGORY", new_group_path, class: "new-category" %>
  </div>
</section>

app/views/groups/new.html.erb
<%= form_with model: @group, url: groups_path, method: :post, local: true, html: { class: "new-category-form" } do |f| %>
  <div class="new-category-header">
    <div class ="back-arrow">
      <%= link_to groups_path do %>
        <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "back-arrow-img" %>
      <% end %>
    </div>
    <h2>ADD CATEGORY</h2>
    <%= f.submit "Create", class: "submit-new-category" %>
  </div>
  <div class="field-name-new-category">
    <%= f.text_field :name, autocomplete: "Group name", placeholder: "Name", class: "login-field" %>
  </div>

  <div class="icon-grid">
    <h2>SELECT AN ICON</h2>
    <div class="icon-row">
      <div class="icon-item">
        <%= f.radio_button :icon, "clothes.png" %>
        <%= label_tag :clothes do %>
          <%= image_tag "clothes.png", alt: "Clothes budget Icon", class: "icon-img" %>
        <% end %>
      </div>
      <div class="icon-item">
        <%= f.radio_button :icon, "entertaiment.png" %>
        <%= label_tag :entertainment do %>
          <%= image_tag "entertaiment.png", alt: "Entertainment budget Icon", class: "icon-img" %>
        <% end %>
      </div>
      <div class="icon-item">
        <%= f.radio_button :icon, "feeding.png" %>
        <%= label_tag :feeding do %>
          <%= image_tag "feeding.png", alt: "Feeding budget Icon", class: "icon-img" %>
        <% end %>
      </div>
    </div>
    <div class="icon-row">
      <div class="icon-item">
        <%= f.radio_button :icon, "house.png" %>
        <%= label_tag :house do %>
          <%= image_tag "house.png", alt: "House budget Icon", class: "icon-img" %>
        <% end %>
      </div>
      <div class="icon-item">
        <%= f.radio_button :icon, "school.png" %>
        <%= label_tag :education do %>
          <%= image_tag "school.png", alt: "Education budget Icon", class: "icon-img" %>
        <% end %>
      </div>
      <div class="icon-item">
        <%= f.radio_button :icon, "transportation.png" %>
        <%= label_tag :transportation do %>
          <%= image_tag "transportation.png", alt: "Transportation budget Icon", class: "icon-img" %>
        <% end %>
      </div>
    </div>
    <div class="icon-row">
      <div class="icon-item">
        <%= f.radio_button :icon, "piggy-bank.png" %>
        <%= label_tag :default do %>
          <%= image_tag "piggy-bank.png", alt: "Default budget Icon", class: "icon-img" %>
        <% end %>
      </div>
    </div>
  </div>

<% end %>

app/views/groups/show.html.erb
<section class="category-container">
  <div class="category-header">
    <div class ="back-arrow">
      <%= link_to groups_path do %>
        <%= image_tag "back_arrow.png", alt: "Back Arrow", class: "back-arrow-img" %>
      <% end %>
    </div>
    <h2>TRANSACTIONS</h2>
    <div class="dummy" >Not</div>
  </div>
  <div class="category-details-container">
    <div class="category-info">
      <div class="group-icon">
        <%= image_tag @group.icon, alt: "Group Icon", class: "group-img"%>
      </div>
      <div class="group-name-container">
        <h3 class="group-name">
          <%= @group.name %>
        </h3>
      </div>
    </div>
    <div class="total-amount-container">
      <p>Total:</p>
      <p>$ <%= @group.entitys.sum(:amount) %></p>
    </div>
    <div class="entities-container">
      <% @entities.each do |entity| %>
        <div class="entity-container">
          <p><%= entity.name %></p>
          <p>$ <%= entity.amount %></p>
        </div>
      <% end %>
    </div>
    <div class="new-entity-container">
      <%= link_to "ADD AN EXPENSE", new_group_entity_path(@group), class: "new-entity" %>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= notice if notice %>
    <%= alert if alert %>
    <%= yield %>
  </body>
</html>

app/views/splashs/index.html.erb
<div class="splash">
  <div class="splash-title">
    <h1>Budget</h1>
  </div>
  <div class="splash-buttons-container">
    <%= button_to "LOG IN", new_user_session_path, class: "splash-button" %>
    <%= button_to "SIGN UP", new_user_registration_path,  method: :get, class: "splash-button" %>
  </div>
</div>